name: CI

on:
  push:
    branches: 
      - master

env:
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: docker build and push
        env: 
          BRANCH: ${{ steps.SetVariables.outputs.branch }}
          CACHEBUST: ${{ github.run_number }}
          TAG_BRANCH: ${{ steps.SetVariables.outputs.tag_branch }}
          TAG_LATEST: ${{ steps.SetVariables.outputs.tag_latest }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          ${WORKFLOW_SCRIPTS_DIR}/docker_build.sh
